version: '3'
services:
    app-nginx:
        build:
            context: ./app/docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./app:/var/www/app
        depends_on:
            - app-php-fpm
        ports:
            - "8080:80"

    app-php-fpm:
        build:
            context: ./app/docker/dev
            dockerfile: php-fpm.docker
        environment:
            APP_DEBUG: 1    
        volumes:
            - ./app:/var/www/app

    app-php-cli:
        build:
            context: ./app/docker/dev
            dockerfile: php-cli.docker
        environment:
            APP_DEBUG: 1     
        volumes:
            - ./app:/var/www/app
            - composer:/root/.composer/cache #кешируем данные composer
        working_dir: /var/www/app

    app-postgres: 
        image: postgres:11.2-alpine
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=app  
        volumes:
            - ./app/var/docker/postgres:/var/lib/postgresql/data
        ports: 
            - "54321:5432"

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - app-postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

volumes:
    composer:  
